from dataclasses import dataclass

@dataclass
class Haiku:
    code: str
    haiku: str

haikus = [
    Haiku("113","Golden sun above,\nClear skies stretch to eternity,\nNature's blissful art."),
    Haiku("116","Soft clouds drift along,\nSun and shade play hide and seek,\nNature's balancing act."),
    Haiku("119","Billowing white puffs,,\nFloating in the endless blue,\nNature's masterpiece."),
    Haiku("122","Grey skies overhead,\nMisty veil shrouds the landscape,\nSerene solitude."),
    Haiku("143", "Veil of misty grey,\nSoftly embracing the earth,\nNature's mystic cloak."),
###### Needs to fill out
    Haiku("176","Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("179","Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("182", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("185", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("200", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("227", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("230", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("248", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("260", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("263", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("266", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("281", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("284", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("293", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("296", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("299", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("302", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("305", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("308", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("311", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("314", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("317", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("320", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("323", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("326", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("329", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("332", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("335", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("338", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("350", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("353", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("356", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("359", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("362", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("365", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("368", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("371", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("374", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("377", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("386", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("389", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("392", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
    Haiku("395", "Cotton clouds up high,\nA blend of sun and shade dance,\nA pleasant balance."),
]